### ISSUE TITLE
Can I use this code?

### ISSUE THREAD

**Issue by gyehuda** [corelight/community-id-spec#1]
This implementation looks great and I'd love to use it in my app. Do you give people permission to use the code? If so, can you add an open source license to the project? I see you have the BSD license on some of the other repos. Adding it to this one would give me permission to use this code.
Thanks!

**Comment by sethhall** [comment]
There is already a COPYING file in place with the license.  It's BSD.

**Comment by gyehuda** [comment]
Thanks. Sorry I missed it.
