### ISSUE TITLE
Include one or two examples in the spec

### ISSUE THREAD

**Issue by andrewthad** [corelight/community-id-spec#19]
At my company, we are enriching traffic logs with community ids with an implementation of this spec that we rolled on our own. It would be nice if the spec included some examples of an input 5-tuple along with the expected community id. Then it would be easy to tell if we implemented the spec correctly.

**Comment by ckreibich** [comment]
That's a great point, thank you. I'll aim to do so (or feel free to submit a PR!). The best list of example values currently exists in the Python implementation's [testsuite](https://github.com/corelight/pycommunityid/blob/master/tests/communityid_test.py#L92-L207).
