### ISSUE TITLE
Missing mapper entry?

### ISSUE THREAD

**Issue by simonemainardi** [corelight/community-id-spec#2]
Is mapper entry

```
 dpkt.icmp.ICMP_RTRADVERT:      dpkt.icmp.ICMP_RTRSOLICIT,
```

missing?

https://github.com/corelight/community-id-spec/blob/bda913f617389df07cdaa23606e11bbd318e265c/community-id.py#L73

**Comment by ckreibich** [comment]
Thank you for flagging this — I think you're right! And this is a direct reflection of Zeek code so I think you may have spotted a problem there as well. I created a ticket over there, mentioning you.

**Comment by ckreibich** [comment]
Oh wow — that's fantastic news Simone! Many thanks for this.
