### ISSUE TITLE
IPv6 

### ISSUE THREAD

**Issue by matthew-renodin** [corelight/community-id-spec#27]
I am writing a program in TypeScript to use the community ID. I have the IPV4 working great, but not so with the IPV6.
I know the python packing runs and works, but is it correct?

I tried to use the verbose mode in the community-id.py to look at the buffer to validate this but it is broken. python community-id.py --no-base64 --verbose pcaps\ipv6.pcap

**Your output produces the following:**

1500000101.216315 | 1:fea15a78047e8057b52988cccd50ec32ffb0814e | 2607:f8b0:400c:c03::1a 2001:470:e5bf:dead:4957:2174:e82c:4887 6 25 63943
1500000101.416173 | 1:fea15a78047e8057b52988cccd50ec32ffb0814e | 2001:470:e5bf:dead:4957:2174:e82c:4887 2607:f8b0:400c:c03::1a 6 63943 25

**My output with my buffer:**
expanded and removed ":" from ip.
r1: 2607f8b0400c0c03000000000000001a
r2: 20010470e5bfdead49572174e82c4887
ArrayBuffer {
  [Uint8Contents]: <00 00 26 07 f8 b0 40 0c 0c 03 00 00 00 00 00 00 00 1a 20 01 04 70 e5 bf de ad 49 57 21 74 e8 2c 48 87 06 00 00 19 f9 c7>,
  byteLength: 40
}
f7aae5da871859418931a2ddfbf7220ecbc50412

**Comment by ckreibich** [comment]
You're almost there Matthew. It looks like you're missing the ordering of the flow tuple endpoints to abstract away packet directionality. For a

    $ community-id 6 2001:470:e5bf:dead:4957:2174:e82c:4887 2607:f8b0:400c:c03::1a 63943 25

I see the following going into the hash buffer:

    00:00
    20:01:04:70:e5:bf:de:ad:49:57:21:74:e8:2c:48:87
    26:07:f8:b0:40:0c:0c:03:00:00:00:00:00:00:00:1a
    06
    00
    f9:c7
    00:19

compared to your

    00 00
    26 07 f8 b0 40 0c 0c 03 00 00 00 00 00 00 00 1a
    20 01 04 70 e5 bf de ad 49 57 21 74 e8 2c 48 87
    06
    00
    00 19
    f9 c7

So the byte values themselves are all correct, but src/dst IP addresses and port numbers are flipped. Community ID flips them so the byte-wise smaller IP/port tuple goes in first.

Btw — it's terrific to see you're working on a TypeScript version! It'd be great if you could share it when you're done — JavaScript & related languages have long been on the most-wanted list for a lot of people.

**Comment by matthew-renodin** [comment]
Yes, that was the issue. I fixed it.

I should be able to post something soon with TS.

**Comment by ckreibich** [comment]
Perfect, looking forward to it.
